version: '3'
services:
  express:
    build: ./elixir
    volumes:
     - /Users/raymaung/Dev/hangman:/code
    working_dir: /code

  db:
    image: "postgres:9.5.7"
    ports:
      - 5555:5432
    # environment:
    #   PGDATA: /var/lib/postgresql/data
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: password
    # volumes:
    #  - ./postgres/pgdata:/var/lib/postgresql/data
